version: '3'
services:
  ner1vah0s:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '5000:5000'
    volumes:
      - ./components:/app/components
      - ./lib:/app/lib
      - ./pages:/app/pages
      - ./server:/app/server
      - ./types:/app/types

