export default {
  BASE_LENGTH: 768,
  NAME_CHUNK_DRAGGED: 'server/NAME_CHUNK_DRAGGED',
  NAME_CHUNK_MOVED: 'NAME_CHUNK_MOVED',
  NAME_CHUNKS_SET: 'NAME_CHUNKS_SET',
  NAME_EL_SET: 'NAME_EL_SET',
  WINDOW_RESIZED: 'WINDOW_RESIZED'
}
